export function buildChallengeInventionPrompt(roundNum, totalRounds, previousChallenges, objective) {
  const previousList = previousChallenges.length > 0
    ? `\n\nPrevious challenges (do NOT repeat these):\n${previousChallenges.map((challenge, index) => `  Round ${index + 1}: ${challenge}`).join('\n')}`
    : '';

  return [
    'You are the JUDGE and MC of Code Arena — a dramatic head-to-head coding tournament.',
    '',
    `This is Round ${roundNum} of ${totalRounds}. You must INVENT a coding challenge for the contestants.`,
    objective ? `\nTournament theme/constraints: ${objective}` : '',
    previousList,
    '',
    'Create an original, interesting coding challenge. It should be completable in a single function or class.',
    'Vary the difficulty and type across rounds — mix algorithms, data structures, utilities, and design patterns.',
    '',
    'You MUST respond with two parts:',
    '',
    '1. First, a dramatic, exciting announcement of the challenge (be theatrical — you\'re the MC!)',
    '',
    '2. Then, at the END of your response, include this EXACT JSON block:',
    '```json',
    '{',
    '  "title": "<catchy challenge title>",',
    '  "description": "<clear, detailed description of what to build, including requirements and edge cases>",',
    '  "difficulty": "Easy" or "Medium" or "Hard",',
    '  "language": "javascript"',
    '}',
    '```',
    '',
    'Make the challenge specific and testable. Include concrete requirements.',
    'The JSON block is parsed by the system — it MUST be valid JSON.',
  ].filter(Boolean).join('\n');
}

export function buildContestantPrompt(challenge, roundNum, totalRounds, contestantName, opponentName) {
  return [
    `You are ${contestantName}, a contestant in Code Arena — a head-to-head coding tournament.`,
    `You are competing against ${opponentName}.`,
    '',
    `This is Round ${roundNum} of ${totalRounds}.`,
    '',
    `## Challenge: ${challenge.title}`,
    `**Difficulty:** ${challenge.difficulty} | **Language:** ${challenge.language}`,
    '',
    challenge.description,
    '',
    'Write your solution now. Your code will be judged against your opponent\'s.',
    '',
    'Requirements:',
    `- Write clean, working ${challenge.language} code`,
    '- Include the complete implementation',
    '- Add brief comments explaining your approach',
    '- Handle edge cases',
    '- Optimize for correctness first, then elegance',
    '',
    'Your entire response should be your code solution wrapped in a code block.',
    'Show your best work — your coding reputation is on the line!',
  ].join('\n');
}

export function buildJudgingPrompt(challenge, roundNum, contestant1, contestant2, solution1, solution2) {
  return [
    `You are the JUDGE in Code Arena. You must evaluate Round ${roundNum}.`,
    '',
    `## Challenge: ${challenge.title}`,
    `${challenge.description}`,
    '',
    '---',
    '',
    `## ${contestant1.displayName}'s Solution:`,
    `\`\`\`${challenge.language}`,
    solution1,
    '```',
    '',
    `## ${contestant2.displayName}'s Solution:`,
    `\`\`\`${challenge.language}`,
    solution2,
    '```',
    '',
    '---',
    '',
    'Evaluate both solutions on these criteria:',
    '1. **Correctness** (40%) — Does it work? Edge cases handled?',
    '2. **Code Quality** (25%) — Clean, readable, well-structured?',
    '3. **Completeness** (20%) — All requirements met?',
    '4. **Elegance** (15%) — Creative approach? Efficient?',
    '',
    'You MUST respond with EXACTLY this JSON format (and nothing else outside the JSON):',
    '```json',
    '{',
    `  "winner": "${contestant1.displayName}" or "${contestant2.displayName}" or "draw",`,
    '  "contestant1Score": <number 0-100>,',
    '  "contestant2Score": <number 0-100>,',
    '  "commentary": "<your dramatic, entertaining verdict — 3-5 sentences>"',
    '}',
    '```',
    '',
    'Be dramatic and entertaining in your commentary. This is a show!',
    'Be fair but decisive. Draws should be rare — pick a winner when possible.',
  ].join('\n');
}
